server:
  port: 8090

chatbot-api:
  cookie: cookie
  csrf: csrf
  gemini-api-key: gemini_api_key

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comment
    username: username
    password: password

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl